### ISSUE TITLE
Add OS-specific shells and commands

### ISSUE THREAD

**Issue by ostev** [arctic-hen7/bonnie#12]
Currently, Bonnie uses `cmd` on Windows, with no option to change it to something else — PowerShell, for instance. This presents difficulties when trying to use the various features of PowerShell. For example, `(get-command pwsh).Path` is valid PowerShell, but `cmd` says that `.Path was unexpected at this time.` This is why I propose the following:

- Add the ability to have customise the shell you're using for a project. I propose a `shell` field be added at the top-level to `bonnie.toml`, as follows:

  ``` toml
  shell = "string" # Normal syntax
  # Or this:
  shell = {
      default = "optional string"
      linux = "optional string"
      macos = "optional string"
      windows = "optional string"
  }   
  ```
  `default` would be used if one or more platforms was not specified; the default for `default` would be the current behaviour.
- Add the ability to have OS-specific commands. This would be useful if you were using equivalent commands on different platforms — `which <command>` and `(get-command <command>).Path` for example. I propose that commands should be able to be specified as a record, as well a string. This would look like the following:
  ``` toml
  [scripts]
  example = "command" # Normal syntax
  # Or this:
  example = {
      default: "optional string"
      linux = "optional string"
      macos = "optional string"
      windows = "optional string"
  }
  ```
  Again, `default` is used if one or more platforms are not specified. If one or more platforms are not specified **and** default is not specified, an error would be thrown.
- Change the default shell on Windows to Windows PowerShell. This would be a breaking change that would bring Bonnie on Windows closer to Bonnie on Linux and macOS — `ls` is not valid `cmd`, but it is valid PowerShell. Modern, open-source PowerShell is probably too new to make the default, but Windows PowerShell has been available since 2006.

**Comment by arctic-hen7** [comment]
Haha I was going to open this exact issue this afternoon! I think a top-level `shell` property is a great idea!

**Comment by arctic-hen7** [comment]
The OS-specific commands proposal may conflict with the subcommand syntax that's in development, so I'll need to think about some way of circumventing it.

**Comment by arctic-hen7** [comment]
One issue I do find is the lack of flexibility with predefining OS strings. Instead, I think it might be better if we had a series of defaults (Windows, MacOS, Linux, maybe BSD), but provided the option of providing a custom Rust target, which gives extreme flexibility over different commands on Musl architecture etc. The only problem would be coming up with a regular expression that can determine a valid target...

**Comment by ostev** [comment]
Perhaps a global per-machine setting would be in order for `shell` — a `~/.bonnie/settings.toml`. I would be interested in implementing this.

**Comment by arctic-hen7** [comment]
Maybe. In the meantime, I have a proposal on OS-specific commands that doesn't conflict with the subcommand syntax.

Default commands are mandatory, but you can specify alternatives for different targets with the `.alts` key (maybe we'll call it something different but whatever for now):
```toml
[scripts]
test = "blah command"
test.alts.windows = "blah command for windows"
test.alts.this-is-an-imaginary-obscure-target = "blah command for obscure system"
```

What are your thoughts on that syntax? The only drawback I immediately see is having default commands be mandatory.
