### ISSUE TITLE
Add command domains

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/bonnie#4]
Right now, Bonnie only supports defining individual commands, however there is a very prevalent use case where we may want to support _command domains_. It's best to show this by example.

Right now, you'd have to do this:
```toml
[scripts]
test = "some unrelated script"
sh-server = "this shells into a server"
sh-db = "this shells into a database"
```

But I think it'd be a good idea to have this be an option:
```toml
[scripts]
test = "some unrelated script"
[scripts.domains.sh]
server = "this shells into a server"
db = "this shells into a database"
```

That way, you'd be able to run the commands like so:
```
bonnie sh server
bonnie sh db
```

This would be a reasonably simple modification to Bonnie's serialization logic. The only issue case would be if a user defines a script and domain with the same name. In that case, we could do one of two things:

1. Run the script if no arguments are given, and the domain if arguments are given.
2. Throw an error.

I think option 2 would be far better and more logical, as otherwise the user simply couldn't define a script with the same name as a domain that takes any arguments, and they wouldn't get any error.
